{% set name = "jrnl" %}
{% set version = "4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jrnl-{{ version }}.tar.gz
  sha256: 980848f9c7ae8d4c844a4cae770c9686b5dda98f479dafac2c3cd72268a53f8b

build:
  entry_points:
    - jrnl = jrnl.main:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.13
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.10.0,<3.13
    - colorama >=0.4
    - cryptography >=3.0
    - keyring >=21.0
    - parsedatetime >=2.6
    - python-dateutil >=2.8.0,<3.0.0
    - pyxdg >=0.27.0
    - ruamel.yaml >=0.17.22
    - rich >=12.2.0,<14.0.0
    - tzlocal >=4.0

test:
  imports:
    - jrnl
  commands:
    - pip check
    - jrnl --help
  requires:
    - pip

about:
  home: https://jrnl.sh
  summary: Collect your thoughts and notes without leaving the command line.
  license: GPL-3.0-only
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - moritzwilksch
